// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTasks(ctx context.Context, id int64) error
	GetTask(ctx context.Context, id int64) (Task, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	UpdateTasks(ctx context.Context, arg UpdateTasksParams) error
}

var _ Querier = (*Queries)(nil)
