// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: todo.sql

package db

import (
	"context"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  title,
  description,
  status,
  due_date
) VALUES (
  $1, $2, $3, $4
) RETURNING id, title, description, status, due_date
`

type CreateTaskParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	DueDate     time.Time `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DueDate,
	)
	return i, err
}

const deleteTasks = `-- name: DeleteTasks :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTasks(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTasks, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, status, due_date FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DueDate,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, status, due_date FROM tasks
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListTasksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTasks = `-- name: UpdateTasks :exec
UPDATE tasks
SET title = $2,
    description = $3,
    status = $4,
    due_date = $5
WHERE id = $1
RETURNING id, title, description, status, due_date
`

type UpdateTasksParams struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	DueDate     time.Time `json:"due_date"`
}

func (q *Queries) UpdateTasks(ctx context.Context, arg UpdateTasksParams) error {
	_, err := q.db.Exec(ctx, updateTasks,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.DueDate,
	)
	return err
}
